### ISSUE TITLE
Implement `Index` (and maybe `IndexMut`) for `Individual`

### ISSUE THREAD

**Issue by daniil-berg** [mfajnberg/tensorevo#26]
### At least read access is required for evolution

We still don't have public access to the layers in the network. We could just make `layers` public, but I think (with the same reasoning as with the call operator) allowing direct index access to them with [`Index`](https://doc.rust-lang.org/std/ops/trait.Index.html) and [`IndexMut`](https://doc.rust-lang.org/std/ops/trait.IndexMut.html) for `Individual` would be fine. I cannot think of anything else that could be deemed "indexable" in the context of an individual. In other words I don't think it would be surprising, if the operation `individual[2]` gave me access to the third (or second, see below) layer in the network.

The benefit over a public `layers` field is that such an interface would not make it possible to change the _number_ of layers in the network. All you could do (with mutable indexing) is modify or replace layers.

The potential risk with either approach is that there is no safeguard against introducing _incompatible_ layers, i.e. ones with weight matrix shapes that are not consistent with their preceding layers, other than checking at runtime. But this is another discussion and not just relegated to layer mutation, but individual construction in general.

Either way, for mutation "**in vivo**" to be possible, we need _some_ form of public access and so far this is the best I could come up with.

A totally different approach would be requiring (to stay with the analogy) an **in vitro** construction of the relevant components of each layer during procreation, i.e. performing crossover and mutation on **tensors** outside of a layer/individual and then assembling them in the constructors `Layer::new`/`Individual::new`. This would only necessitate immutable/read access to those components (just the `Index` trait).

Maybe the latter approach is preferable, since this would mitigate the risk of accidentally "genetically crippling" an individual after creation. Considering the topology to be the _genome_, making it effectively immutable would line up nicely with nature. In other words, after birth, an individual may only learn (modify the weights and biases), never gain neurons or connections.

---

### Number of layers conundrum

The question that remains for me is what to do about the so called "input layer" (which we currently only have implicitly).
Should the index `0` then return the first hidden layer? Or a "stub" input layer? Or panic?
Related: Should the `num_layers` method return the number excluding or including the implicit input layer?

We could of course just store a trivial identity layer with every individual as the first element in the `layers` vector.
Assuming the weight matrix of the first hidden layer has `N` columns, such an "actual" input layer would have to have a `N x N` identity weight matrix (1 diagonal, 0 everywhere else) and a zero-bias vector of size `N`, as well as the `identity` activation function.
Though this layer would of course have to be completely ignored both when feeding forward and during gradient descend since it is just unnecessary for both.
I would at least alleviate the ambiguity about the layer number.
We could even easily create and add such a layer ourselves inside the `Individual::new` constructor based on the first (hidden) layer passed to it.

But maybe this is just unnecessary and we could just very clearly document (in line with what we already do) that the input layer is always implicit and the number of layers always excludes the input layer and the `0`-th index will give the first hidden layer.

Since this question is directly tied to indexing, I formulate it as part of this issue.

**Comment by mfajnberg** [comment]
We'll have to chat about what exactly could constitute an input layer in the foreseeable future. Currently, I see no reason to include one explicitly as part of `Individual`, let alone as part of the collection of 'hidden' layers. Especially for simple use cases.

I like the idea of accessing layers using the `Index` trait via `Individual`. Confusion may arise whenever there are varying segments of different kinds of layers within an individual. But since there are no plans right now for that, I believe this'll work just fine.

**Comment by jsf116** [comment]
I agree with Max.
